### ISSUE TITLE
External memory bus bandwidth, external memory latency, cache size

### ISSUE THREAD

**Issue by orent** [karlrupp/microprocessor-trend-data#2]
The widening CPU/memory speed disparity is an important piece of the picture. 

Can this information be extracted programmatically from your collection of datasheets or does it require manual labor?

**Comment by karlrupp** [comment]
The data are not sufficiently detailed in this repository for what you are looking for.

However, you can find memory bandwidth comparisons (in particular arithmetic intensity) in this more detailed collection: https://github.com/karlrupp/cpu-gpu-mic-comparison (see in particular the blog post referenced therein)
