### ISSUE TITLE
42 years ?

### ISSUE THREAD

**Issue by fgm** [karlrupp/microprocessor-trend-data#3]
Hello. Thanks for compiling these data.
Is there any reason why the dataset and article mention "42 years" while they actually cover late 1971 to late 2017, i.e. 46 years instead of 42 ?

**Comment by karlrupp** [comment]
Good catch. Looks like this is an historic artifact. I started with the `35 years of ...` image and data for the 5 and 7 years, respectively. The next update should have this fixed - thanks for bringing this up!

**Comment by karlrupp** [comment]
Thanks, @fgm , fixed with the latest update: https://github.com/karlrupp/microprocessor-trend-data/commit/47382e2e3c653d71ebae66d8e8aecc088866543d
