### ISSUE TITLE
Will there be a 44 (or 48) year version?

### ISSUE THREAD

**Issue by Sebastian-Maier** [karlrupp/microprocessor-trend-data#5]
Hello. Thanks for sharing this figure (and the corresponding data) with us.
I would like to ask whether you plan a new/updated 2020 version of the figure?

In case you need help, just give me a hint which data sources you used in the past.
(I have already seen some URLs in the newdata.txt file.)

**Comment by fprimezero** [comment]
Hi, yeah, I'm thinking about an update in the near future.

One thing is a bit tricky: For the latest processors there are no more SpecINT 2006 entries available, only numbers for the more recent 2017 edition of the benchmark. Making a smooth transition between the SpecINT editions is needed. (But well, CPUs prior to 2006 also have approximated SpecINT 2006 performance numbers...)

**Comment by karlrupp** [comment]
Hi,
yes, I'm thinking about doing a 44-year edition in the near future.

It will require some transition from SpecINT 2006 to SpecINT 2017, as the latest processors don't report numbers for the old 2006 edition anymore. As SpecINT 2006 numbers for processors prior to 2006 are also approximate, this shouldn't be a big problem.

**Comment by karlrupp** [comment]
Here is the 48-year update: https://github.com/karlrupp/microprocessor-trend-data/commit/47382e2e3c653d71ebae66d8e8aecc088866543d
